import type { CreditCard } from "./schema";

/**
 * Hand-curated Canadian credit card dataset for NorthTap recommendations.
 *
 * ILLUSTRATIVE / REPRESENTATIVE ONLY — rates, fees, caps, and signup bonuses change
 * frequently and may be out of date relative to issuer terms. Verify against the
 * issuer before any real financial decision. `lastVerified` is a spot-check date,
 * not a guarantee of currency.
 */
export const CARDS: CreditCard[] = [
  // ── American Express ──────────────────────────────────────────────
  {
    id: "amex-cobalt",
    issuer: "American Express",
    name: "Cobalt",
    annualFee: 155.4,
    pointCurrency: "Amex MR",
    network: "Amex",
    tier: "Premium",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Earn up to 30,000 MR points in first year with spend",
      estimatedValueCad: 720,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 5, capMonthly: 2500 },
      { category: "dining", earnRate: 5, capMonthly: 2500 },
      { category: "transit", earnRate: 5, capMonthly: 2500 },
      { category: "entertainment", earnRate: 5, capMonthly: 2500 },
      { category: "drugstore", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "travel", earnRate: 2 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "amex-gold",
    issuer: "American Express",
    name: "Gold Rewards",
    annualFee: 150,
    pointCurrency: "Amex MR",
    network: "Amex",
    tier: "Premium",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "25,000 MR points after meeting spend threshold",
      estimatedValueCad: 600,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "amex-aeroplan-reserve",
    issuer: "American Express",
    name: "Aeroplan Reserve",
    annualFee: 599,
    pointCurrency: "Aeroplan",
    network: "Amex",
    tier: "Ultra Premium",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "70,000 Aeroplan points + first-year benefits",
      estimatedValueCad: 1400,
    },
    rewardCategories: [
      { category: "travel", earnRate: 3 },
      { category: "dining", earnRate: 2 },
      { category: "groceries", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "transit", earnRate: 1.5 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "amex-aeroplan",
    issuer: "American Express",
    name: "Aeroplan",
    annualFee: 120,
    pointCurrency: "Aeroplan",
    network: "Amex",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "40,000 Aeroplan points after qualifying spend",
      estimatedValueCad: 800,
    },
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "groceries", earnRate: 1.25 },
      { category: "gas", earnRate: 1.25 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "amex-simplycash",
    issuer: "American Express",
    name: "SimplyCash",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Amex",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1.25 },
      { category: "gas", earnRate: 1.25 },
      { category: "dining", earnRate: 1.25 },
      { category: "travel", earnRate: 1.25 },
      { category: "transit", earnRate: 1.25 },
      { category: "drugstore", earnRate: 1.25 },
      { category: "recurring_bills", earnRate: 1.25 },
      { category: "entertainment", earnRate: 1.25 },
      { category: "foreign_currency", earnRate: 1.25 },
      { category: "other", earnRate: 1.25 },
    ],
  },
  {
    id: "amex-simplycash-preferred",
    issuer: "American Express",
    name: "SimplyCash Preferred",
    annualFee: 99,
    pointCurrency: "cashback",
    network: "Amex",
    tier: "Preferred",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "dining", earnRate: 1.25 },
      { category: "travel", earnRate: 1.25 },
      { category: "transit", earnRate: 1.25 },
      { category: "drugstore", earnRate: 1.25 },
      { category: "recurring_bills", earnRate: 1.25 },
      { category: "entertainment", earnRate: 1.25 },
      { category: "foreign_currency", earnRate: 1.25 },
      { category: "other", earnRate: 1.25 },
    ],
  },
  {
    id: "amex-green",
    issuer: "American Express",
    name: "Green",
    annualFee: 0,
    pointCurrency: "Amex MR",
    network: "Amex",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── TD ────────────────────────────────────────────────────────────
  {
    id: "td-aeroplan-vi",
    issuer: "TD",
    name: "Aeroplan Visa Infinite",
    annualFee: 139,
    pointCurrency: "Aeroplan",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "35,000 Aeroplan points after spend",
      estimatedValueCad: 700,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 1.5 },
      { category: "dining", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "td-aeroplan-vip",
    issuer: "TD",
    name: "Aeroplan Visa Infinite Privilege",
    annualFee: 599,
    pointCurrency: "Aeroplan",
    network: "Visa",
    tier: "Visa Infinite Privilege",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "groceries", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "td-cash-back-vi",
    issuer: "TD",
    name: "Cash Back Visa Infinite",
    annualFee: 120,
    pointCurrency: "cashback",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 3, capMonthly: 1000 },
      { category: "recurring_bills", earnRate: 3, capMonthly: 1000 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "td-rewards-visa",
    issuer: "TD",
    name: "Rewards Visa",
    annualFee: 0,
    pointCurrency: "TD Rewards",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "td-first-class-travel",
    issuer: "TD",
    name: "First Class Travel Visa Infinite",
    annualFee: 139,
    pointCurrency: "TD Rewards",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 3 },
      { category: "dining", earnRate: 2 },
      { category: "groceries", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── CIBC ──────────────────────────────────────────────────────────
  {
    id: "cibc-aeroplan-vi",
    issuer: "CIBC",
    name: "Aeroplan Visa Infinite",
    annualFee: 139,
    pointCurrency: "Aeroplan",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "35,000 Aeroplan points after spend",
      estimatedValueCad: 700,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 1.5 },
      { category: "dining", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-dividend-vi",
    issuer: "CIBC",
    name: "Dividend Visa Infinite",
    annualFee: 120,
    pointCurrency: "cashback",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 4, capMonthly: 500 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-dividend",
    issuer: "CIBC",
    name: "Dividend Visa",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-aventura-vi",
    issuer: "CIBC",
    name: "Aventura Visa Infinite",
    annualFee: 139,
    pointCurrency: "CIBC Aventura",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "groceries", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-aventura-gold",
    issuer: "CIBC",
    name: "Aventura Gold Visa",
    annualFee: 120,
    pointCurrency: "CIBC Aventura",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 1.5 },
      { category: "dining", earnRate: 1.25 },
      { category: "groceries", earnRate: 1.25 },
      { category: "gas", earnRate: 1.25 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Scotiabank ────────────────────────────────────────────────────
  {
    id: "scotia-gold-amex",
    issuer: "Scotiabank",
    name: "Gold American Express",
    annualFee: 120,
    pointCurrency: "Scene+",
    network: "Amex",
    tier: "Gold",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "40,000 Scene+ points after spend",
      estimatedValueCad: 400,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 5, capMonthly: 2000 },
      { category: "entertainment", earnRate: 5, capMonthly: 2000 },
      { category: "dining", earnRate: 3 },
      { category: "transit", earnRate: 2 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "scotia-passport-vi",
    issuer: "Scotiabank",
    name: "Passport Visa Infinite",
    annualFee: 150,
    pointCurrency: "Scene+",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "35,000 Scene+ points + no FX fee",
      estimatedValueCad: 350,
    },
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 2 },
      { category: "entertainment", earnRate: 2 },
      { category: "foreign_currency", earnRate: 2 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "scotia-momentum-vi",
    issuer: "Scotiabank",
    name: "Momentum Visa Infinite",
    annualFee: 120,
    pointCurrency: "cashback",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 4, capMonthly: 500 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "transit", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "scotia-scene-visa",
    issuer: "Scotiabank",
    name: "Scene+ Visa",
    annualFee: 0,
    pointCurrency: "Scene+",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "entertainment", earnRate: 5 },
      { category: "dining", earnRate: 2 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── RBC ───────────────────────────────────────────────────────────
  {
    id: "rbc-avion-vi",
    issuer: "RBC",
    name: "Avion Visa Infinite",
    annualFee: 120,
    pointCurrency: "RBC Avion",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "35,000 Avion points after spend",
      estimatedValueCad: 595,
    },
    rewardCategories: [
      { category: "travel", earnRate: 1.25 },
      { category: "dining", earnRate: 1.25 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "rbc-avion-vip",
    issuer: "RBC",
    name: "Avion Visa Infinite Privilege",
    annualFee: 499,
    pointCurrency: "RBC Avion",
    network: "Visa",
    tier: "Visa Infinite Privilege",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 1.5 },
      { category: "dining", earnRate: 1.5 },
      { category: "groceries", earnRate: 1.25 },
      { category: "gas", earnRate: 1.25 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "rbc-cashback",
    issuer: "RBC",
    name: "Cash Back Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "rbc-iono",
    issuer: "RBC",
    name: "Ion+",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "recurring_bills", earnRate: 2 },
      { category: "groceries", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── BMO ───────────────────────────────────────────────────────────
  {
    id: "bmo-eclipse-vi",
    issuer: "BMO",
    name: "eclipse Visa Infinite",
    annualFee: 120,
    pointCurrency: "BMO Rewards",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "35,000 BMO Rewards points after spend",
      estimatedValueCad: 245,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 5, capMonthly: 1000 },
      { category: "transit", earnRate: 4 },
      { category: "dining", earnRate: 3 },
      { category: "entertainment", earnRate: 3 },
      { category: "gas", earnRate: 2 },
      { category: "travel", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "bmo-ascend-we",
    issuer: "BMO",
    name: "Ascend World Elite Mastercard",
    annualFee: 150,
    pointCurrency: "BMO Rewards",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 5 },
      { category: "dining", earnRate: 3 },
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "transit", earnRate: 2 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "bmo-cashback",
    issuer: "BMO",
    name: "CashBack Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 3, capMonthly: 500 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "bmo-air-miles-we",
    issuer: "BMO",
    name: "AIR MILES World Elite Mastercard",
    annualFee: 99,
    pointCurrency: "AIR MILES",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Rogers / Tangerine / PC / Simplii / Neo / Canadian Tire ───────
  {
    id: "rogers-red-we",
    issuer: "Rogers",
    name: "Red World Elite Mastercard",
    annualFee: 0,
    pointCurrency: "Rogers",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Earn Rogers dollars back on eligible spend",
      estimatedValueCad: 100,
    },
    rewardCategories: [
      { category: "recurring_bills", earnRate: 1.5 },
      { category: "groceries", earnRate: 1.5 },
      { category: "dining", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "transit", earnRate: 1.5 },
      { category: "drugstore", earnRate: 1.5 },
      { category: "entertainment", earnRate: 1.5 },
      { category: "foreign_currency", earnRate: 1.5 },
      { category: "other", earnRate: 1.5 },
    ],
  },
  {
    id: "tangerine-moneyback",
    issuer: "Tangerine",
    name: "Money-Back Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      // Three free categories chosen by user — model as strong everyday picks
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "dining", earnRate: 0.5 },
      { category: "travel", earnRate: 0.5 },
      { category: "transit", earnRate: 0.5 },
      { category: "drugstore", earnRate: 0.5 },
      { category: "entertainment", earnRate: 0.5 },
      { category: "foreign_currency", earnRate: 0.5 },
      { category: "other", earnRate: 0.5 },
    ],
  },
  {
    id: "pc-financial-we",
    issuer: "PC Financial",
    name: "PC Mastercard World Elite",
    annualFee: 0,
    pointCurrency: "PC Optimum",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 3 },
      { category: "drugstore", earnRate: 3 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "pc-financial",
    issuer: "PC Financial",
    name: "PC Mastercard",
    annualFee: 0,
    pointCurrency: "PC Optimum",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "drugstore", earnRate: 2 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "simplii-cashback",
    issuer: "Simplii",
    name: "Cash Back Visa",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 4, capMonthly: 500 },
      { category: "recurring_bills", earnRate: 1.5 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 0.5 },
      { category: "travel", earnRate: 0.5 },
      { category: "transit", earnRate: 0.5 },
      { category: "drugstore", earnRate: 0.5 },
      { category: "entertainment", earnRate: 0.5 },
      { category: "foreign_currency", earnRate: 0.5 },
      { category: "other", earnRate: 0.5 },
    ],
  },
  {
    id: "neo-mastercard",
    issuer: "Neo",
    name: "Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "neo-world-elite",
    issuer: "Neo",
    name: "World Elite Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1.5 },
      { category: "dining", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "triangle-we",
    issuer: "Canadian Tire",
    name: "Triangle World Elite Mastercard",
    annualFee: 0,
    pointCurrency: "Triangle",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "gas", earnRate: 4 },
      { category: "groceries", earnRate: 2 },
      { category: "drugstore", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "triangle-mastercard",
    issuer: "Canadian Tire",
    name: "Triangle Mastercard",
    annualFee: 0,
    pointCurrency: "Triangle",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "gas", earnRate: 2.5 },
      { category: "groceries", earnRate: 1.5 },
      { category: "drugstore", earnRate: 1.5 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── National Bank / Desjardins / HSBC (WestJet) ───────────────────
  {
    id: "nbc-world-elite",
    issuer: "National Bank",
    name: "World Elite Mastercard",
    annualFee: 150,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 5, capMonthly: 500 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "desjardins-odyssey-gold",
    issuer: "Desjardins",
    name: "Odyssey Gold Mastercard",
    annualFee: 130,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "hsbc-westjet-we",
    issuer: "HSBC",
    name: "World Elite WestJet Mastercard",
    annualFee: 89,
    pointCurrency: "WestJet",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Additional American Express ───────────────────────────────────
  {
    id: "amex-platinum",
    issuer: "American Express",
    name: "Platinum Card",
    annualFee: 799,
    pointCurrency: "Amex MR",
    network: "Amex",
    tier: "Ultra Premium",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Large MR welcome bonus after qualifying spend (offer varies)",
      estimatedValueCad: 1200,
    },
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "amex-marriott-bonvoy",
    issuer: "American Express",
    name: "Marriott Bonvoy",
    annualFee: 120,
    pointCurrency: "Marriott Bonvoy",
    network: "Amex",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Bonvoy points after meeting first-year spend",
      estimatedValueCad: 400,
    },
    rewardCategories: [
      { category: "travel", earnRate: 3 },
      { category: "dining", earnRate: 2 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "amex-business-gold",
    issuer: "American Express",
    name: "Business Gold Rewards",
    annualFee: 250,
    pointCurrency: "Amex MR",
    network: "Amex",
    tier: "Business",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "MR points after qualifying business spend",
      estimatedValueCad: 500,
    },
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "groceries", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Additional TD ─────────────────────────────────────────────────
  {
    id: "td-cash-back-visa",
    issuer: "TD",
    name: "Cash Back Visa",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "dining", earnRate: 0.5 },
      { category: "travel", earnRate: 0.5 },
      { category: "transit", earnRate: 0.5 },
      { category: "drugstore", earnRate: 0.5 },
      { category: "entertainment", earnRate: 0.5 },
      { category: "foreign_currency", earnRate: 0.5 },
      { category: "other", earnRate: 0.5 },
    ],
  },
  {
    id: "td-aeroplan-visa",
    issuer: "TD",
    name: "Aeroplan Visa",
    annualFee: 60,
    pointCurrency: "Aeroplan",
    network: "Visa",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Aeroplan points after qualifying spend",
      estimatedValueCad: 400,
    },
    rewardCategories: [
      { category: "travel", earnRate: 1.5 },
      { category: "dining", earnRate: 1.25 },
      { category: "groceries", earnRate: 1.25 },
      { category: "gas", earnRate: 1.25 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "td-rewards-visa-infinite",
    issuer: "TD",
    name: "Rewards Visa Infinite",
    annualFee: 120,
    pointCurrency: "TD Rewards",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 3 },
      { category: "gas", earnRate: 3 },
      { category: "recurring_bills", earnRate: 3 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Additional CIBC ───────────────────────────────────────────────
  {
    id: "cibc-costco-mc",
    issuer: "CIBC",
    name: "Costco Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      // Costco gas / Costco warehouse earn elevated cashback; model gas + groceries high
      { category: "gas", earnRate: 3, capAnnual: 7000 },
      { category: "groceries", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-aeroplan-visa",
    issuer: "CIBC",
    name: "Aeroplan Visa",
    annualFee: 60,
    pointCurrency: "Aeroplan",
    network: "Visa",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Aeroplan points after qualifying spend",
      estimatedValueCad: 400,
    },
    rewardCategories: [
      { category: "travel", earnRate: 1.5 },
      { category: "dining", earnRate: 1.25 },
      { category: "groceries", earnRate: 1.25 },
      { category: "gas", earnRate: 1.25 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-dividend-vip",
    issuer: "CIBC",
    name: "Dividend Visa Infinite Privilege",
    annualFee: 499,
    pointCurrency: "cashback",
    network: "Visa",
    tier: "Visa Infinite Privilege",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 4, capMonthly: 1000 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "travel", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "cibc-aventura-vip",
    issuer: "CIBC",
    name: "Aventura Visa Infinite Privilege",
    annualFee: 499,
    pointCurrency: "CIBC Aventura",
    network: "Visa",
    tier: "Visa Infinite Privilege",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 3 },
      { category: "dining", earnRate: 2 },
      { category: "groceries", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Additional Scotiabank ─────────────────────────────────────────
  {
    id: "scotia-scene-vi",
    issuer: "Scotiabank",
    name: "Scene+ Visa Infinite",
    annualFee: 120,
    pointCurrency: "Scene+",
    network: "Visa",
    tier: "Visa Infinite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Scene+ points after qualifying spend",
      estimatedValueCad: 300,
    },
    rewardCategories: [
      { category: "entertainment", earnRate: 5 },
      { category: "dining", earnRate: 3 },
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "scotia-momentum",
    issuer: "Scotiabank",
    name: "Momentum Visa",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Visa",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2, capMonthly: 500 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 0.5 },
      { category: "travel", earnRate: 0.5 },
      { category: "transit", earnRate: 0.5 },
      { category: "drugstore", earnRate: 0.5 },
      { category: "entertainment", earnRate: 0.5 },
      { category: "foreign_currency", earnRate: 0.5 },
      { category: "other", earnRate: 0.5 },
    ],
  },
  {
    id: "scotia-platinum-amex",
    issuer: "Scotiabank",
    name: "Platinum American Express",
    annualFee: 200,
    pointCurrency: "Scene+",
    network: "Amex",
    tier: "Platinum",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Scene+ points + travel credits (offer varies)",
      estimatedValueCad: 500,
    },
    rewardCategories: [
      { category: "travel", earnRate: 3 },
      { category: "dining", earnRate: 3 },
      { category: "groceries", earnRate: 2 },
      { category: "entertainment", earnRate: 2 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Additional RBC ────────────────────────────────────────────────
  {
    id: "rbc-westjet-we",
    issuer: "RBC",
    name: "WestJet World Elite Mastercard",
    annualFee: 119,
    pointCurrency: "WestJet",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "WestJet dollars after qualifying spend",
      estimatedValueCad: 300,
    },
    rewardCategories: [
      { category: "travel", earnRate: 2 },
      { category: "dining", earnRate: 1.5 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "rbc-avion-gold",
    issuer: "RBC",
    name: "Avion Gold Visa",
    annualFee: 120,
    pointCurrency: "RBC Avion",
    network: "Visa",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Avion points after qualifying spend",
      estimatedValueCad: 400,
    },
    rewardCategories: [
      { category: "travel", earnRate: 1.25 },
      { category: "dining", earnRate: 1.25 },
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "rbc-ion",
    issuer: "RBC",
    name: "Ion",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "recurring_bills", earnRate: 1 },
      { category: "groceries", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "rbc-cashback-preferred",
    issuer: "RBC",
    name: "Cash Back Preferred World Elite Mastercard",
    annualFee: 99,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1.5 },
      { category: "gas", earnRate: 1.5 },
      { category: "recurring_bills", earnRate: 1.5 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── Additional BMO ────────────────────────────────────────────────
  {
    id: "bmo-air-miles",
    issuer: "BMO",
    name: "AIR MILES Mastercard",
    annualFee: 0,
    pointCurrency: "AIR MILES",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "bmo-cashback-we",
    issuer: "BMO",
    name: "CashBack World Elite Mastercard",
    annualFee: 120,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 5, capMonthly: 500 },
      { category: "transit", earnRate: 4 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "bmo-preferred-rate",
    issuer: "BMO",
    name: "Preferred Rate Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      // Low-rate card; model token cashback for ranking completeness
      { category: "groceries", earnRate: 0.5 },
      { category: "dining", earnRate: 0.5 },
      { category: "gas", earnRate: 0.5 },
      { category: "travel", earnRate: 0.5 },
      { category: "transit", earnRate: 0.5 },
      { category: "drugstore", earnRate: 0.5 },
      { category: "recurring_bills", earnRate: 0.5 },
      { category: "entertainment", earnRate: 0.5 },
      { category: "foreign_currency", earnRate: 0.5 },
      { category: "other", earnRate: 0.5 },
    ],
  },

  // ── Additional Desjardins / National Bank ─────────────────────────
  {
    id: "desjardins-odyssey-we",
    issuer: "Desjardins",
    name: "Odyssey World Elite Mastercard",
    annualFee: 150,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 3 },
      { category: "gas", earnRate: 2 },
      { category: "dining", earnRate: 2 },
      { category: "travel", earnRate: 2 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "desjardins-bonus",
    issuer: "Desjardins",
    name: "Bonus Dollars Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 1 },
      { category: "gas", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "nbc-allure",
    issuer: "National Bank",
    name: "Allure World Elite Mastercard",
    annualFee: 150,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "travel", earnRate: 4 },
      { category: "dining", earnRate: 3 },
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },

  // ── MBNA ──────────────────────────────────────────────────────────
  {
    id: "mbna-rewards-we",
    issuer: "MBNA",
    name: "Rewards World Elite Mastercard",
    annualFee: 120,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    welcomeOffer: {
      summary: "Statement credit / points after spend (offer varies)",
      estimatedValueCad: 200,
    },
    rewardCategories: [
      { category: "groceries", earnRate: 5, capMonthly: 500 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 2 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
  {
    id: "mbna-smart-cash",
    issuer: "MBNA",
    name: "Smart Cash World Elite Mastercard",
    annualFee: 0,
    pointCurrency: "cashback",
    network: "Mastercard",
    tier: "World Elite",
    lastVerified: "2026-09-20",
    rewardCategories: [
      { category: "groceries", earnRate: 2 },
      { category: "gas", earnRate: 2 },
      { category: "recurring_bills", earnRate: 1 },
      { category: "dining", earnRate: 1 },
      { category: "travel", earnRate: 1 },
      { category: "transit", earnRate: 1 },
      { category: "drugstore", earnRate: 1 },
      { category: "entertainment", earnRate: 1 },
      { category: "foreign_currency", earnRate: 1 },
      { category: "other", earnRate: 1 },
    ],
  },
];

export function getCardById(id: string): CreditCard | undefined {
  return CARDS.find((c) => c.id === id);
}

export function getCardsByIssuer(issuer: string): CreditCard[] {
  return CARDS.filter((c) => c.issuer === issuer);
}

export function groupCardsByIssuer(
  cards: CreditCard[] = CARDS,
): Record<string, CreditCard[]> {
  return cards.reduce<Record<string, CreditCard[]>>((acc, card) => {
    const list = acc[card.issuer] ?? [];
    list.push(card);
    acc[card.issuer] = list;
    return acc;
  }, {});
}
