/**
 * Generates supabase/migrations/20260923000001_seed_catalog.sql from
 * packages/core static catalogs. Run from repo root:
 *
 *   NORTHTAP_SEED_API_KEY=… pnpm seed:catalog
 *
 * NORTHTAP_SEED_API_KEY is required for the api_keys hash row. Never commit
 * the plaintext — only the SHA-256 hash is written into the migration.
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CARDS } from "../packages/core/src/cards.ts";
import {
  LOYALTY_PROGRAMS,
  MERCHANT_BRANDS,
  MERCHANT_PARTNERSHIPS,
} from "../packages/core/src/partnerships.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(
  __dirname,
  "../supabase/migrations/20260923000001_seed_catalog.sql",
);

const SEED_API_KEY = process.env.NORTHTAP_SEED_API_KEY?.trim();
if (!SEED_API_KEY) {
  console.error(
    "Set NORTHTAP_SEED_API_KEY in the environment (e.g. from .env.local) before regenerating the seed. The plaintext must never be committed.",
  );
  process.exit(1);
}
function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown): string {
  return `${sqlStr(JSON.stringify(value))}::jsonb`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return `'{}'::text[]`;
  return `ARRAY[${values.map(sqlStr).join(", ")}]::text[]`;
}

function sqlNullable(value: string | null | undefined): string {
  return value == null ? "null" : sqlStr(value);
}

function sqlNum(value: number): string {
  return String(value);
}

const verifiedAt = "now()";
const status = `'verified'::public.catalog_status`;

const cardRows = CARDS.map((c) => {
  return `  (
    ${sqlStr(c.id)},
    ${sqlStr(c.name)},
    ${sqlStr(c.issuer)},
    ${sqlNum(c.annualFee)},
    ${sqlStr(c.pointCurrency)},
    ${sqlJson(c.rewardCategories)},
    ${c.welcomeOffer ? sqlJson(c.welcomeOffer) : "null"},
    ${sqlNullable(c.network ?? null)},
    ${sqlNullable(c.tier ?? null)},
    ${sqlStr(c.lastVerified)}::date,
    ${verifiedAt},
    ${verifiedAt},
    ${status}
  )`;
}).join(",\n");

const programRows = LOYALTY_PROGRAMS.map((p) => {
  return `  (
    ${sqlStr(p.id)},
    ${sqlStr(p.name)},
    ${sqlNullable(p.description ?? null)},
    ${sqlNullable(p.pointCurrency ?? null)},
    ${sqlStr(p.sourceUrl)},
    ${sqlStr(p.lastVerified)}::date,
    ${verifiedAt},
    ${verifiedAt},
    ${status}
  )`;
}).join(",\n");

const brandRows = MERCHANT_BRANDS.map((b) => {
  return `  (
    ${sqlStr(b.id)},
    ${sqlStr(b.name)},
    ${sqlStr(b.category)},
    ${sqlNullable(b.operator ?? null)},
    ${sqlNullable(b.notes ?? null)},
    ${sqlStr(b.sourceUrl)},
    ${sqlStr(b.lastVerified)}::date,
    ${verifiedAt},
    ${verifiedAt},
    ${status}
  )`;
}).join(",\n");

const partnershipRows = MERCHANT_PARTNERSHIPS.map((p) => {
  return `  (
    ${sqlStr(p.id)},
    ${sqlTextArray(p.merchantBrandIds)},
    ${sqlNullable(p.loyaltyProgramId)},
    ${sqlTextArray(p.cardIds)},
    ${sqlStr(p.affiliation)},
    ${sqlStr(p.requirements)},
    ${sqlJson(p.benefits)},
    ${p.stacksWithCardCategoryRewards},
    ${sqlNullable(p.notes ?? null)},
    ${sqlTextArray(p.sourceUrls)},
    ${sqlStr(p.lastVerified)}::date,
    ${verifiedAt},
    ${verifiedAt},
    ${status}
  )`;
}).join(",\n");

const keyHash = createHash("sha256").update(SEED_API_KEY, "utf8").digest("hex");
const keyPrefix = SEED_API_KEY.slice(0, 12);

const sql = `-- Generated by scripts/generate-catalog-seed.ts — do not edit by hand.
-- Source: packages/core CARDS / MERCHANT_BRANDS / LOYALTY_PROGRAMS / MERCHANT_PARTNERSHIPS.
-- Regenerate: NORTHTAP_SEED_API_KEY=… pnpm seed:catalog

-- Seed verified catalog rows
insert into public.cards (
  id, name, issuer, annual_fee, point_currency, reward_categories,
  welcome_offer, network, tier, last_verified, captured_at, verified_at, status
) values
${cardRows}
on conflict (id) do update set
  name = excluded.name,
  issuer = excluded.issuer,
  annual_fee = excluded.annual_fee,
  point_currency = excluded.point_currency,
  reward_categories = excluded.reward_categories,
  welcome_offer = excluded.welcome_offer,
  network = excluded.network,
  tier = excluded.tier,
  last_verified = excluded.last_verified,
  verified_at = excluded.verified_at,
  status = excluded.status;

insert into public.loyalty_programs (
  id, name, description, point_currency, source_url, last_verified,
  captured_at, verified_at, status
) values
${programRows}
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  point_currency = excluded.point_currency,
  source_url = excluded.source_url,
  last_verified = excluded.last_verified,
  verified_at = excluded.verified_at,
  status = excluded.status;

insert into public.merchant_brands (
  id, name, category, operator, notes, source_url, last_verified,
  captured_at, verified_at, status
) values
${brandRows}
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  operator = excluded.operator,
  notes = excluded.notes,
  source_url = excluded.source_url,
  last_verified = excluded.last_verified,
  verified_at = excluded.verified_at,
  status = excluded.status;

insert into public.merchant_partnerships (
  id, brand_ids, loyalty_program_id, card_ids, affiliation, requirements,
  benefits, stacks_with_card_category_rewards, notes, source_urls,
  last_verified, captured_at, verified_at, status
) values
${partnershipRows}
on conflict (id) do update set
  brand_ids = excluded.brand_ids,
  loyalty_program_id = excluded.loyalty_program_id,
  card_ids = excluded.card_ids,
  affiliation = excluded.affiliation,
  requirements = excluded.requirements,
  benefits = excluded.benefits,
  stacks_with_card_category_rewards = excluded.stacks_with_card_category_rewards,
  notes = excluded.notes,
  source_urls = excluded.source_urls,
  last_verified = excluded.last_verified,
  verified_at = excluded.verified_at,
  status = excluded.status;

-- Internal Expo / NorthTap API key: hash only in this migration.
-- Plaintext lives in Vercel / local .env.local (NORTHTAP_STATIC_API_KEY /
-- EXPO_PUBLIC_NORTHTAP_API_KEY / NORTHTAP_SEED_API_KEY) — never commit it.
insert into public.api_keys (
  key_hash, key_prefix, owner_label, tier, rate_limit_per_minute, active
) values (
  ${sqlStr(keyHash)},
  ${sqlStr(keyPrefix)},
  'NorthTap Expo (internal)',
  'internal'::public.api_key_tier,
  600,
  true
)
on conflict (key_hash) do update set
  owner_label = excluded.owner_label,
  tier = excluded.tier,
  rate_limit_per_minute = excluded.rate_limit_per_minute,
  active = excluded.active;
`;

writeFileSync(outPath, sql, "utf8");
console.log(
  `Wrote ${outPath} (${CARDS.length} cards, ${MERCHANT_BRANDS.length} brands, ${LOYALTY_PROGRAMS.length} programs, ${MERCHANT_PARTNERSHIPS.length} partnerships)`,
);
console.log(`Seed API key prefix: ${keyPrefix}… (hash ${keyHash.slice(0, 12)}…)`);
